modLoader="javafml"
loaderVersion="[1,)"
license="All Rights Reserved"

[[mods]]
modId="neobackup"
version="1.0.0"
displayName="NeoBackup"
authors="maomer"
description='''
A server-only backup mod for NeoForge 1.21.1
'''

[[dependencies.neobackup]]
    modId="neoforge"
    type="required"
    versionRange="[21.0.167,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.neobackup]]
    modId="minecraft"
    type="required"
    versionRange="[1.21]"
    ordering="NONE"
    side="SERVER"